### ISSUE TITLE
Testing with pre-trained model

### ISSUE THREAD

**Issue by fasogbon** [hyk1996/Single-Human-Parsing-LIP#1]
Thank you for this work. Is there any way I can test this code with a pre-trained model provides by you? Thanks

**Comment by fasogbon** [comment]
I.e ./checkpoint folder content

**Comment by Yukun-Huang** [comment]
I will release the pre-trained model on google drive and baidu drive, please check out later.

**Comment by fasogbon** [comment]
Patiently waiting. Thanks

**Comment by Yukun-Huang** [comment]
Already updated, you can find the link below or in _README.md_.
[Google Drive](https://drive.google.com/drive/folders/13DzOvUoIx0JR-BTEilhLqdAIp3h0H5Zj)

**Comment by anantaarora** [comment]
Hi,
Can you provide me the resnet152 based pre-trained model?

**Comment by bob251** [comment]
Resnet-101 model is giving size mismatch error. Can you recommend something which might help?
![image](https://user-images.githubusercontent.com/35396477/101258750-91505280-374a-11eb-8fdf-94c2bb8727a4.png)

**Comment by Yukun-Huang** [comment]
> Resnet-101 model is giving size mismatch error. Can you recommend something which might help?
> ![image](https://user-images.githubusercontent.com/35396477/101258750-91505280-374a-11eb-8fdf-94c2bb8727a4.png)

Fixed, you might download the latest version of code and model weights then retry it.
