### ISSUE TITLE
download pretrained model

### ISSUE THREAD

**Issue by yuyijie1995** [hyk1996/Single-Human-Parsing-LIP#12]
Hi, I already downloaded your weight from Cloud and put it  in the checkpoints/densenet/PSPNet_last ,but the model will still download the backbone pretrained model from internet . How can I avoid download it.

**Comment by Yukun-Huang** [comment]
You can set _pretrained=False_ in [net/extractors.py](https://github.com/hyk1996/Single-Human-Parsing-LIP/blob/00c43cf3d5b0e3748cf93dd08de2591932bad10d/net/extractors.py#L32).
