### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by nicolas-dufour** [hyk1996/Single-Human-Parsing-LIP#14]
Hi,
I'm trying to retrieve the LIP dataset but the link provided seems to be dead.
Do you happen to provide a backup solution?

Thanks

**Comment by Dxlstudy** [comment]
Have you get the dataset?

**Comment by elerator** [comment]
Hi I also look for the dataset. I found it on the website https://www.payititi.com/ but it's all in chinese and you appear to need a chinese phone number to register for download. Can anybody provide a working download link for Europe?

**Comment by elerator** [comment]
https://zhuanlan.zhihu.com/p/342369686
