### ISSUE TITLE
Can you provide predict.py version to test one sample (without labels)?

### ISSUE THREAD

**Issue by vic9527** [hyk1996/Single-Human-Parsing-LIP#2]
Hello,

How to test a non-label sample, not use the lip.py.

I am looking forward to your ability to provide such a function.

**Comment by Yukun-Huang** [comment]
I think you want to test the model on an image file? You can easily implement the function you want with PIL (or opencv) and numpy. PIL is for image loading and numpy for transforming data format.

**Comment by Yukun-Huang** [comment]
Already provided.
