### ISSUE TITLE
Meeting a question

### ISSUE THREAD

**Issue by HQQ197060** [hyk1996/Single-Human-Parsing-LIP#4]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.i s_available() is False. If you are running on a CPU-only machine, please use tor ch.load with map_location=torch.device('cpu') to map your storages to the CPU.
good moring ,sir, how to solve this question,thank you?

**Comment by Yukun-Huang** [comment]
It seems that you don't have a CUDA environment, please configure correctly first. If you want to run the code on CPU (not recommended), you can simply modify the code to remove `.cuda()`.

**Comment by HQQ197060** [comment]
Oh. Appreciate




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kevin.h"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月17日(星期四) 上午10:49
收件人:&nbsp;"hyk1996/Single-Human-Parsing-LIP"<Single-Human-Parsing-LIP@noreply.github.com&gt;;
抄送:&nbsp;"黄倩倩"<836895752@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hyk1996/Single-Human-Parsing-LIP] Meeting a question (#4)




It seems that you don't have a CUDA environment, please configure correctly first. If you want to run the code on CPU (not recommended), you can simply modify the code to remove .cuda().
