### ISSUE TITLE
ask quesdtion

### ISSUE THREAD

**Issue by HQQ197060** [hyk1996/Single-Human-Parsing-LIP#5]
Hello, I have another problem: the input picture is 1928×1448, slightly modify your inference. Py runs to generate result.jpg only shows "pred", but the size of "pred" is 640×480.What I want is the input of 1928×1448, and the output of result.jpg is also 1928×1448. How should I solve it?Thank you .

**Comment by Yukun-Huang** [comment]
I think opencv or PIL is more suitable for your need, matplotlib is hard to use for saving a predict map. You can send me an email for more details.

**Comment by HQQ197060** [comment]
ok thanks,This problem has been solved using the CV2.resize function in opencv.In addition, I would like to ask you about the principle of the official SSL algorithm. The key is to detect the 9 jointss of the human body.My topic is to divide the upper body chest area and the waist area. I don't understand the dividing principle of my topic.  Looking forward to your reply.

**Comment by Yukun-Huang** [comment]
I am not very familiar with the SSL algorithm, this repository is based on PSPNet. I think you can re-divide the existing predict maps into desired areas. For instance, the waist area can be taken as the boundary between the upper body and the lower body.

**Comment by HQQ197060** [comment]
OK.thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kevin.h"<notifications@github.com&gt;; 
发送时间: 2019年11月17日(星期天) 下午5:11
收件人: "hyk1996/Single-Human-Parsing-LIP"<Single-Human-Parsing-LIP@noreply.github.com&gt;; 
抄送: "黄倩倩"<836895752@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyk1996/Single-Human-Parsing-LIP] ask quesdtion (#5)




I am not very familiar with the SSL algorithm, this repository is based on PSPNet. I think you can re-divide the existing predict maps into desired areas. For instance, the waist area can be taken as the boundary between the upper body and the lower body.

**Comment by HQQ197060** [comment]
Hello, I would like to ask if your paper for this project is "PSPNet: Pyramid Scene Parsing Network"?Is the dataset used to be look into person? thanks

**Comment by Yukun-Huang** [comment]
Yes, our model is based on PSPNet, and we use Look Into Person dataset for evaluation.

**Comment by HQQ197060** [comment]
Is the training set you use for training also Look Into Person dataset?If I use your GitHub project to train my network to identify the human burst area and waist area, the network trained by my data training can be divided correctly, but I don't quite understand the principle, I would like to consult with you, thank you.If I use your GitHub project to train my network to identify the human chest area and waist area, the network trained by my data training can be divided correctly, but I don't quite understand the principle, I would like to consult with you, thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kevin.h"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 晚上8:26
收件人: "hyk1996/Single-Human-Parsing-LIP"<Single-Human-Parsing-LIP@noreply.github.com&gt;; 
抄送: "黄倩倩"<836895752@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyk1996/Single-Human-Parsing-LIP] ask quesdtion (#5)




Yes, our model is based on PSPNet, and we use Look Into Person dataset for evaluation.

**Comment by Yukun-Huang** [comment]
Yes, I also use the trainset of the Look Into Person dataset. You can email me for more details. (kunh6414@gmail.com)
