### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by wtingfeng** [hyk1996/Single-Human-Parsing-LIP#6]
Hello,I use your model to train my own datasets.In your experience , how many pictures to be trained can I get a correct result for parsing?

**Comment by Yukun-Huang** [comment]
Recommended to use more than 10,000 images.

**Comment by wtingfeng** [comment]
Thanks for your reply！ At present，all of the datasets are labeled by myself，i can't get so many pictures by internet or open sources. So if i create more datasets by rotating pictures or changing backgroud on the basis of existed pictures，will the parsing result be badly affected？


| |
冯琬婷
|
|
邮箱：wting_feng@163.com
|

签名由 网易邮箱大师 定制

On 05/26/2020 20:47, Kevin.h wrote:

Recommended to use more than 10,000 images.

**Comment by Yukun-Huang** [comment]
You can pretrain the model with LIP and fine-tune on your own dataset, and data argumentation is also useful for insufficient data.

PS. for more details, you can email me in Chinese. (kunh6414@gmail.com)

**Comment by wtingfeng** [comment]
Get it！Thanks for your recommendation！


| |
冯琬婷
|
|
邮箱：wting_feng@163.com
|

签名由 网易邮箱大师 定制

On 05/26/2020 22:00, Kevin.h wrote:

You can pretrain the model with LIP and fine-tune on your own dataset, and data argumentation is also useful for insufficient data.

PS. for more details, you can email me in Chinese. (kunh6414@gmail.com)
