### ISSUE TITLE
The result

### ISSUE THREAD

**Issue by StevenqrYang** [hyk1996/Single-Human-Parsing-LIP#7]
Except  the visualized result by use eval.py, how can I get the digitalized result for further usage?

**Comment by Yukun-Huang** [comment]
"pred" in [https://github.com/hyk1996/Single-Human-Parsing-LIP/blob/master/eval.py#L250](url) is the result.

**Comment by StevenqrYang** [comment]
Very grateful for your last answer! I find that the digitalized result in "pred" is limited in the size of (256,256). But the following procedure require the array of original size, (720*1080) for example, and how can I get the origin-sized array?

**Comment by Yukun-Huang** [comment]
The provided pre-trained model only supports the size of 256x256. You may need to retrain the model with the new input size 720x1080. In addition, directly resizing the prediction result is also a solution.
