### ISSUE TITLE
重叠区域的划分

### ISSUE THREAD

**Issue by wtingfeng** [hyk1996/Single-Human-Parsing-LIP#9]
对于一个图片，因为会有遮挡和重叠的问题，那么其实图片上的某一个像素可能同属于多个划分的类别，但是好像您的这个方法对于一个像素点只有识别出属于一个类别？

**Comment by Yukun-Huang** [comment]
它可以得到像素点对应的各个类别的概率，选取最大值后才是最终的预测类别。当然你说的问题确实存在，现有的分割数据集也很少会有这种多类别的标注。
